### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by andmax** [xamyzhao/brainstorm#12]
Hi Amy, I think it would be good to clear state the dependencies: Python 3 (3.5+?), a number of python packages, such as $ pip install opencv-python nibabel tqdm pydot, and GraphViz software

**Comment by ChuxiJ** [comment]
Ask the same questions!

**Comment by MarsVillage** [comment]
Hi @xamyzhao , thanks a lot for sharing the codes. Could you please kindly specify the version of python, tensorflow, and keras used in this project? It would be helpful for people who are trying to use the codes. Thanks so much!

**Comment by xamyzhao** [comment]
Thanks for the reminder! I updated the readme.
