### ISSUE TITLE
meaning of 'flow-fwd' , 'flow-bck' , 'flow-bidir 'and  'color-unet'

### ISSUE THREAD

**Issue by amberhappy** [xamyzhao/brainstorm#16]
'flow-fwd' can learn spatial transform,and 'color-unet' learn appearence transform, what about   'flow-bck' , 'flow-bidir '? And what's the different between these models?

**Comment by xamyzhao** [comment]
Sorry, I missed this message! flow-bck is used to train the appearance transform -- it simply learns a subject-to-atlas spatial transform function. flow-bidir is meant to include the functionality of flow-fwd and flow-bck, but it does not fit on most GPUs.
