### ISSUE TITLE
Has been the code completed until now?

### ISSUE THREAD

**Issue by daa233** [xamyzhao/brainstorm#2]
Hi, thanks for your excellent work! Since the repo is released recently, I wonder if it is complete and ready to run the code and train the model till now?

**Comment by xamyzhao** [comment]
Thanks for checking! The code is complete, but I will be checking in some reorganization and refactoring in the next few days. I would recommend waiting for that commit.

**Comment by Qingyuncookie** [comment]
In the 35nd line of the main.py, there is a key "use_subjects_as_source" whose content is ['OASIS_OAS1_0327_MR1_mri_talairach_orig'], I have searched all the files and can't find this file. I'm not sure if this is a MRI data or not, and I don't understand what it is used for, please help me, thank you very much !

**Comment by libo1712** [comment]
hi，i want to know what  configure  requirements if i‘m ready to run the code. THANKS

**Comment by bruce25796** [comment]
In the first example: `python main.py trans --gpu 0 --data mri-100-csts2 --model flow-bds` where is the model  flow-bds?  If there is no, where can I find a substitute? Thanks

**Comment by xamyzhao** [comment]
@libo1712, you'll need to provide your own dataset (scans and segmentations) and put them into the directories specified in mri_loader.py. I'll be uploading a more detailed dataset/training configuration guide this week.
