### ISSUE TITLE
Check failed: dims == sizes.size() (5 vs. 4)

### ISSUE THREAD

**Issue by zhao706** [xamyzhao/brainstorm#23]
Hello, I encountered the following problems while running the main.py. Do you know why？
2020-06-26 11:00:27.306985: F .\tensorflow/core/util/mkl_util.h:636] Check failed: dims == sizes.size() (5 vs. 4)

**Comment by xamyzhao** [comment]
It seems like the network is getting the wrong size as input. Can you check
that the input is batch_size x h x w x d x 1?

**Comment by zhao706** [comment]
Yes,I checked the input is (batch_size,h,w,d,1).I guess it's about the version, so what's your version of tensorflow？

**Comment by xamyzhao** [comment]
Can you include your input arguments here? I can try to repro the error.

**Comment by zhao706** [comment]
Thank you very much for your help. I solved this problem by reducing the version of tensorflow from 1.14.1 to 1.13.0.And I found that the code has a high memory requirement.

**Comment by zhao706** [comment]
Hello, I have a doubt is what criteria you choose with label data?





------------------ Original ------------------

**Comment by xamyzhao** [comment]
Are you asking how I chose the labeled example to use as our atlas? We picked an example that was close to the mean subject in the dataset (which was computed using standard atlas-building techniques).
