### ISSUE TITLE
Generation of Segmentation Labels

### ISSUE THREAD

**Issue by nikku1234** [xamyzhao/brainstorm#29]
Can you please share the freesurfer commands to do the Preprocessing told in the paper? 

Reference from the paper : "we resample the brains to 256 × 256 × 256 with 1mm isotropic voxels,
and affinely align and crop the images to 160 × 192 × 224. We do not apply any intensity corrections, and we perform
skull-stripping by zeroing out voxels with no anatomical label".

**Comment by adalca** [comment]
we use `recon-all` in FreeSurfer, but we used a FreeSurfer version no longer maintained..  

We just released a dataset (images and segmentations) just recently if that's useful.

**Comment by nikku1234** [comment]
Okay.Thank you for the reply. If possible can you share the dataset link?

**Comment by adalca** [comment]
sure, I put up the readme here: https://github.com/adalca/medical-datasets/blob/master/neurite-oasis.md
