### ISSUE TITLE
AttributeError: 'ResourceSummaryWriter' object has no attribute 'add_summary'

### ISSUE THREAD

**Issue by WwwwJX** [xamyzhao/brainstorm#31]
can you tell me how to solve this question????
AttributeError: 'ResourceSummaryWriter' object has no attribute 'add_summary'

**Comment by xamyzhao** [comment]
I believe that error comes from the tensorboard code, so you should just be able to comment out the add_summary call if you don't plan on using tensorboard.

**Comment by WwwwJX** [comment]
Thank you, and if I want to use this code how can i debug? I search the internet and find nearly nothing about this question, sorry to trouble you

**Comment by xamyzhao** [comment]
It seems like ResourceSummaryWriter was renamed. You can search for where add_summary was used in the code and try to find the name of the function in newer versions of tensorflow.
