### ISSUE TITLE
UnboundLocalError: local variable 'X_source' referenced before assignment

### ISSUE THREAD

**Issue by LIKP0** [xamyzhao/brainstorm#35]
![image](https://user-images.githubusercontent.com/56829276/200307423-94d55073-76a2-4f61-98e4-2273f189bf8b.png)

Hello! I have tried a long time but I still can't figure out this problem. It seems like I have some problems with my dataset. I use standard OASIS dataset, and I convert the 'nii.gz' files to '.npz' files myself. And I also modify the key value of the npz files. Could you give me any help?
![image](https://user-images.githubusercontent.com/56829276/200308067-98224150-6687-426d-aca2-881e0250dad8.png)

**Comment by adalca** [comment]
Can you tell us what debugging you have tried? 

It does seem like X_source doesn't get computed, so it may be worth looking at `self.X_source_train.shape[0]`

**Comment by LIKP0** [comment]
Thank you! I will try it! What's more, I notice the "average template atlas" mentioned in your paper, which is more similar to all MRI images. Is it the "OASIS1-MRI327" one in the citation in main.py?



---Original---
From: "Adrian ***@***.***&gt;
Date: Mon, Nov 7, 2022 21:04 PM
To: ***@***.***&gt;;
Cc: "JiaLin ***@***.******@***.***&gt;;
Subject: Re: [xamyzhao/brainstorm] UnboundLocalError: local variable'X_source' referenced before assignment (Issue #35)




 
Can you tell us what debugging you have tried?
 
It does seem like X_source doesn't get computed, so it may be worth looking at self.X_source_train.shape[0]

**Comment by adalca** [comment]
I'll let @xamyzhao answer that one :)

**Comment by LIKP0** [comment]
This one, please!
![image](https://user-images.githubusercontent.com/56829276/200454016-5117d904-50b8-40a6-b516-57823bb23bb9.png)

**Comment by xamyzhao** [comment]
@LIKP0 yes, the comment in the code indicates the atlas that we used in the paper.

Have you modified the argument 'use_subjects_as_source', or is the code still looking for a volume named "atlas"?

**Comment by LIKP0** [comment]
Thanks for your reply! I will try to handle the bug. Another question is that I can't make it very clearly about the "inverse-warped" in the apperance model. Does it mean:
1. Warp the unlabelled data to atlas using the pretrained spatial transform model.
2. Do apperance transform to atlas to train to match with the inverse-warpped unlabelled subject
![image](https://user-images.githubusercontent.com/56829276/200501655-3e0639b8-6d09-434c-8033-cb65f9b865f6.png)
But in this way, we need to train another spatial transform model warpping the unlabelled image to atlas since the previous spatial model is trained to warp atlas to unlabelled image. Is it true?
