### ISSUE TITLE
No training model files

### ISSUE THREAD

**Issue by bruce25796** [xamyzhao/brainstorm#4]
In the first example: 

`python main.py trans --gpu 0 --data mri-100-csts2 --model flow-bds` 

 where is the model flow-bds? If there is no, where can I find a substitute? 
Thanks

**Comment by xamyzhao** [comment]
That line of code is intended to train a spatial transform model with the parameters under the key "flow-bds". "flow-bds" is simply the short name I've chosen for the bidirectional flow model. You can find the full set of parameters in main.py. 

I have not included any pre-trained models in this repo. I will be uploading a more detailed dataset/training guide soon, though.
