### ISSUE TITLE
pydot error.

### ISSUE THREAD

**Issue by chengjianhong** [xamyzhao/brainstorm#5]
@xamyzhao Hi, thanks for your excellent work. But when I run `python main.py trans --gpu 1 --data mri-100unlabeled --model flow-bidir `by default, there are following errors. 

> stdout, stderr:
>  b''
> b'Format: "jpg" not recognized. Use one of: canon cmap cmapx cmapx_np dot dot_json eps fig gv imap imap_np ismap json json0 mp pdf pic plain plain-ext png pov ps ps2 svg svgz tk vml vmlz xdot xdot1.2 xdot1.4 xdot_json\n'
> 
> Traceback (most recent call last):
>   File "main.py", line 337, in <module>
>     test_every_n_epochs=test_every_n_epochs)
>   File "/root/userfolder/workspace_python/brainstorm/src/experiment_engine.py", line 109, in run_experiment
>     exp.create_models()
>   File "/root/userfolder/workspace_python/brainstorm/src/transform_models.py", line 442, in create_models
>     super(TransformModelTrainer, self).create_models()
>   File "/root/userfolder/workspace_python/brainstorm/src/experiment_base.py", line 77, in create_models
>     self._print_models()
>   File "/root/userfolder/workspace_python/brainstorm/src/experiment_base.py", line 161, in _print_models
>     show_shapes=True)
>   File "/root/userfolder/anaconda3/lib/python3.6/site-packages/keras/utils/vis_utils.py", line 138, in plot_model
>     dot.write(to_file, format=extension)
>   File "/root/userfolder/anaconda3/lib/python3.6/site-packages/pydot.py", line 1817, in write
>     s = self.create(prog, format, encoding=encoding)
>   File "/root/userfolder/anaconda3/lib/python3.6/site-packages/pydot.py", line 1945, in create
>     assert process.returncode == 0, process.returncode
> AssertionError: 1
>

**Comment by xamyzhao** [comment]
It seems that this might be an issue with your pydot or graphviz installation: https://stackoverflow.com/questions/33678636/pydot-error-file-format-png-not-recognized. Alternatively, you could remove the calls to plot_model -- they are useful for debugging your network architecture, but not necessary for training.

**Comment by Liiiii2101** [comment]
@xamyzhao Hi, Amy! Thanks for your great job! When I run python main.py trans --gpu 1 --data mri-100unlabeled --model flow-bidir , I got the error as follows, but I think the input shape is supposed to be (None, 160,192,224,1) right? Or do I miss something?

Traceback (most recent call last):
  File "main.py", line 355, in <module>
    test_every_n_epochs=test_every_n_epochs)
  File "/Users/apple/brainstorm-master/src/experiment_engine.py", line 133, in run_experiment
    run_metadata=None,
  File "/Users/apple/brainstorm-master/src/experiment_engine.py", line 184, in train_batch_by_batch
    joint_loss, joint_loss_names = exp.train_on_batch()
  File "/Users/apple/brainstorm-master/src/transform_models.py", line 589, in train_on_batch
    loss_vals = self.transform_model.train_on_batch(X, Y)
  File "/Users/apple/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1826, in train_on_batch
    check_batch_axis=True)
  File "/Users/apple/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1411, in _standardize_user_data
    exception_prefix='target')
  File "/Users/apple/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 153, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking target: expected vm2_cc_fwd to have shape (None, 160, 192, 224, 3) but got array with shape (1, 160, 192, 224, 1)

Thank you very much!

**Comment by chengjianhong** [comment]
@xamyzhao Dear Amy, thanks for your reply. But there is still a problem. It seems to be  the OOM error. The free memory of my GPU is about 11.7GB, unfortunately It happens this. Can you tell me what is your GPU configuration or how to avoid it ?


> 2019-05-02 22:42:07.649458: I tensorflow/core/common_runtime/bfc_allocator.cc:680] Stats: 
> Limit:                 11918963508
> InUse:                  9581529856
> MaxInUse:               9608116992
> NumAllocs:                    1702
> MaxAllocSize:           1321205760
> 
> 2019-05-02 22:42:07.649560: W tensorflow/core/common_runtime/bfc_allocator.cc:279] ********___************____**************************************************____*******************
> 2019-05-02 22:42:07.649622: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at conv_ops_3d.cc:398 : Resource exhausted: OOM when allocating tensor with shape[1,32,160,192,224] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
> Traceback (most recent call last):
>   File "main.py", line 337, in <module>
>     test_every_n_epochs=test_every_n_epochs)
>   File "/root/userfolder/workspace_python/brainstorm/src/experiment_engine.py", line 133, in run_experiment
>     run_metadata=None,
>   File "/root/userfolder/workspace_python/brainstorm/src/experiment_engine.py", line 184, in train_batch_by_batch
>     joint_loss, joint_loss_names = exp.train_on_batch()
>   File "/root/userfolder/workspace_python/brainstorm/src/transform_models.py", line 569, in train_on_batch
>     loss_vals = self.transform_model.train_on_batch(X, Y)
>   File "/root/userfolder/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1217, in train_on_batch
>     outputs = self.train_function(ins)
>   File "/root/userfolder/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
>     return self._call(inputs)
>   File "/root/userfolder/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
>     fetched = self._callable_fn(*array_vals)
>   File "/root/userfolder/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1454, in __call__
>     self._session._session, self._handle, args, status, None)
>   File "/root/userfolder/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
>     c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1,160,192,224,32] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
> 	 [[Node: vm2_cc_bck/unet_dec_conv3D_3_0/convolution = Conv3D[T=DT_FLOAT, _class=["loc:@train...ropInputV2"], data_format="NDHWC", dilations=[1, 1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1, 1], _device="/job:localhost/replica:0/task:0/device:GPU:0"](vm2_cc_bck/leaky_re_lu_7/LeakyRelu, unet_dec_conv3D_3_0/kernel/read)]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
> 
> 	 [[Node: loss/vm2_cc_fwd_loss/Mean_3/_621 = _Recv[client_terminated=false,recv_device="/job:localhost/replica:0/task:0/device:CPU:0",send_device="/job:localhost/replica:0/task:0/device:GPU:0",send_device_incarnation=1,tensor_name="edge_16995_loss/vm2_cc_fwd_loss/Mean_3", tensor_type=DT_FLOAT,_device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

**Comment by xamyzhao** [comment]
@chengjianhong I just added a flow-fwd and flow-bck option to train the two spatial models separately if they don't both fit on the GPU (simply replace --model flow-bidir with --model flow-fwd). Let me know if you run into any issues.

**Comment by xamyzhao** [comment]
@Liiiii2101 can you also try using --model flow-fwd instead of --model flow-bidir? Thanks.

**Comment by chengjianhong** [comment]
@xamyzhao Dear Amy. I run it according to your suggestion. The error is as follow.

> 2019-05-03 12:45:16.718132: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11366 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:83:00.0, compute capability: 6.1)
> Traceback (most recent call last):
>   File "main.py", line 199, in <module>
>     arch_params = named_arch_params[args.model]
> KeyError: 'flow-fwd'

**Comment by xamyzhao** [comment]
@chengjianhong can you check if you pulled the latest version?

**Comment by Liiiii2101** [comment]
Hi, Amy! After using --model flow-bidir, I still got the same error:
Traceback (most recent call last):
  File "main.py", line 355, in <module>
    test_every_n_epochs=test_every_n_epochs)
  File "/Users/apple/brainstorm-master/src/experiment_engine.py", line 133, in run_experiment
    run_metadata=None,
  File "/Users/apple/brainstorm-master/src/experiment_engine.py", line 184, in train_batch_by_batch
    joint_loss, joint_loss_names = exp.train_on_batch()
  File "/Users/apple/brainstorm-master/src/transform_models.py", line 589, in train_on_batch
    loss_vals = self.transform_model.train_on_batch(X, Y)
  File "/Users/apple/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1826, in train_on_batch
    check_batch_axis=True)
  File "/Users/apple/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1411, in _standardize_user_data
    exception_prefix='target')
  File "/Users/apple/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 153, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking target: expected flow to have shape (None, 160, 192, 224, 3) but got array with shape (1, 160, 192, 224, 1)

**Comment by xamyzhao** [comment]
@Liiiii2101 did you try my suggestion of using --model flow-fwd instead of --model flow-bidir? I will be deprecating support for flow-bidir since it does not fit on many standard GPUs.

**Comment by jacobxchan** [comment]
Hi, Amy.

I am also facing OOM issues even after using --model flow-fwd.
I have only 8GB on my GPU.
Stats:
Limit:                  9117697966
InUse:                  7311111168
MaxInUse:               7751514112
NumAllocs:                    1699
MaxAllocSize:           1321205760

Is there any workaround on this?

Thanks!

**Comment by TaoZhong11** [comment]
> Hi, Amy! After using --model flow-bidir, I still got the same error:
> Traceback (most recent call last):
> File "main.py", line 355, in
> test_every_n_epochs=test_every_n_epochs)
> File "/Users/apple/brainstorm-master/src/experiment_engine.py", line 133, in run_experiment
> run_metadata=None,
> File "/Users/apple/brainstorm-master/src/experiment_engine.py", line 184, in train_batch_by_batch
> joint_loss, joint_loss_names = exp.train_on_batch()
> File "/Users/apple/brainstorm-master/src/transform_models.py", line 589, in train_on_batch
> loss_vals = self.transform_model.train_on_batch(X, Y)
> File "/Users/apple/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1826, in train_on_batch
> check_batch_axis=True)
> File "/Users/apple/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1411, in _standardize_user_data
> exception_prefix='target')
> File "/Users/apple/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 153, in _standardize_input_data
> str(array.shape))
> ValueError: Error when checking target: expected flow to have shape (None, 160, 192, 224, 3) but got array with shape (1, 160, 192, 224, 1)

Hi Amy,

When I try to train transform models I have used all these three commands, including --model flow-fwd, -bck and -bidir, but there is a similar error:
Traceback (most recent call last):
  File "main.py", line 357, in <module>
    test_every_n_epochs=test_every_n_epochs)
  File "/home/taozhong/下载/brainstorm-master/src/experiment_engine.py", line 133, in run_experiment
    run_metadata=None,
  File "/home/taozhong/下载/brainstorm-master/src/experiment_engine.py", line 184, in train_batch_by_batch
    joint_loss, joint_loss_names = exp.train_on_batch()
  File "/home/taozhong/下载/brainstorm-master/src/transform_models.py", line 589, in train_on_batch
    loss_vals = self.transform_model.train_on_batch(X, Y)
  File "/home/taozhong/.local/lib/python3.6/site-packages/keras/engine/training.py", line 1826, in train_on_batch
    check_batch_axis=True)
  File "/home/taozhong/.local/lib/python3.6/site-packages/keras/engine/training.py", line 1411, in _standardize_user_data
    exception_prefix='target')
  File "/home/taozhong/.local/lib/python3.6/site-packages/keras/engine/training.py", line 153, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking target: expected flow to have shape (None, 160, 192, 224, 3) but got array with shape (1, 160, 192, 224, 1)

**Comment by TaoZhong11** [comment]
> > Hi, Amy! After using --model flow-bidir, I still got the same error:
> > Traceback (most recent call last):
> > File "main.py", line 355, in
> > test_every_n_epochs=test_every_n_epochs)
> > File "/Users/apple/brainstorm-master/src/experiment_engine.py", line 133, in run_experiment
> > run_metadata=None,
> > File "/Users/apple/brainstorm-master/src/experiment_engine.py", line 184, in train_batch_by_batch
> > joint_loss, joint_loss_names = exp.train_on_batch()
> > File "/Users/apple/brainstorm-master/src/transform_models.py", line 589, in train_on_batch
> > loss_vals = self.transform_model.train_on_batch(X, Y)
> > File "/Users/apple/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1826, in train_on_batch
> > check_batch_axis=True)
> > File "/Users/apple/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1411, in _standardize_user_data
> > exception_prefix='target')
> > File "/Users/apple/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 153, in _standardize_input_data
> > str(array.shape))
> > ValueError: Error when checking target: expected flow to have shape (None, 160, 192, 224, 3) but got array with shape (1, 160, 192, 224, 1)
> 
> Hi Amy,
> 
> When I try to train transform models I have used all these three commands, including --model flow-fwd, -bck and -bidir, but there is a similar error:
> Traceback (most recent call last):
> File "main.py", line 357, in
> test_every_n_epochs=test_every_n_epochs)
> File "/home/taozhong/下载/brainstorm-master/src/experiment_engine.py", line 133, in run_experiment
> run_metadata=None,
> File "/home/taozhong/下载/brainstorm-master/src/experiment_engine.py", line 184, in train_batch_by_batch
> joint_loss, joint_loss_names = exp.train_on_batch()
> File "/home/taozhong/下载/brainstorm-master/src/transform_models.py", line 589, in train_on_batch
> loss_vals = self.transform_model.train_on_batch(X, Y)
> File "/home/taozhong/.local/lib/python3.6/site-packages/keras/engine/training.py", line 1826, in train_on_batch
> check_batch_axis=True)
> File "/home/taozhong/.local/lib/python3.6/site-packages/keras/engine/training.py", line 1411, in _standardize_user_data
> exception_prefix='target')
> File "/home/taozhong/.local/lib/python3.6/site-packages/keras/engine/training.py", line 153, in _standardize_input_data
> str(array.shape))
> ValueError: Error when checking target: expected flow to have shape (None, 160, 192, 224, 3) but got array with shape (1, 160, 192, 224, 1)

When I update my keras2.1.1 to 2.1.2, this problem was solved. But that happened another error:
7] Stats: 
Limit:                 10304582452
InUse:                  7629312768
MaxInUse:               9841424128
NumAllocs:                    1623
MaxAllocSize:           1321205760
......
	 [[{{node loss/vm2_cc_fwd_loss_1/Mean_5/_523}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_16989_loss/vm2_cc_fwd_loss_1/Mean_5", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
Even when I tried all these three model type (-fwd, -bck and bidir) it still happen.

**Comment by TaoZhong11** [comment]
> Hi, Amy.
> 
> I am also facing OOM issues even after using --model flow-fwd.
> I have only 8GB on my GPU.
> Stats:
> Limit: 9117697966
> InUse: 7311111168
> MaxInUse: 7751514112
> NumAllocs: 1699
> MaxAllocSize: 1321205760
> 
> Is there any workaround on this?
> 
> Thanks!

Hi,

Have you solved this problem?

**Comment by xamyzhao** [comment]
@jacobxchan @TaoZhong11 I trained my models with a 12GB GPU (sorry, I need to update the requirements in the README). With 8GB, you will likely need to spatially downsample your training volumes.

**Comment by TaoZhong11** [comment]
> @jacobxchan @TaoZhong11 I trained my models with a 12GB GPU (sorry, I need to update the requirements in the README). With 8GB, you will likely need to spatially downsample your training volumes.

I crop the training volume to 144x148x188 and run it in 1080ti, 12G and this errors still happen.

**Comment by TaoZhong11** [comment]
> @jacobxchan @TaoZhong11 I trained my models with a 12GB GPU (sorry, I need to update the requirements in the README). With 8GB, you will likely need to spatially downsample your training volumes.

I further downsample  the data and the model finally work. Thank you for your excellent work!
