### ISSUE TITLE
supervised: local variable referenced before assignment

### ISSUE THREAD

**Issue by BorisMansencal** [xamyzhao/brainstorm#6]
Hi,

I am trying to use your code on a different dataset.
I have several segmented images that I would like to use for training.
I run the following command:
python3 main.py trans --gpu 1 --data mri-supervised --model flow-fwd
I have changed src/mri_loader.py to correctly load my data (I also had to change the vol_size in src/transform_models.py ).
I have slightly changed the 'mri-supervised' configuration:
```
    'mri-supervised': {  # supervised experiment
        'use_labels': my_labels,
        'use_atlas_as_source': False,
        'use_subjects_as_source': [],
        'do_load_test': False,
        'img_shape': (181, 217, 181, 1),
        'n_shot': 3, 
        'n_unlabeled': 0,
        'n_validation': 2,
        'do_preload_vols': True,
        'aug_in_gen': True,
        'n_tm_aug': None,
        'n_flow_aug': None,
        'warp_labels': True,
    },
```

Thus in my loaded dataset, I have:
```
vols_unlabeled_train.shape = (0, 181, 217, 181, 1)
vols_labeled_train.shape = (3, 181, 217, 181, 1)
vols_labeled_valid.shape = (2, 181, 217, 181, 1)
```

When I run the script, I have the following error: 
```
[2019-05-07 14:38:31] TransformModel_mri_source_3l_0ul_flow_fwd_grad_l2-regfwt1_cc_vm-win9-wt1 training epoch 0/501
Traceback (most recent call last):
  File "main.py", line 358, in <module>
    test_every_n_epochs=test_every_n_epochs)
  File "/home/mansenca/VOLBRAIN/brainstorm_git/src/experiment_engine.py", line 133, in run_experiment
    run_metadata=None,
  File "/home/mansenca/VOLBRAIN/brainstorm_git/src/experiment_engine.py", line 222, in train_batch_by_batch
    if batch_count >= 10:
UnboundLocalError: local variable 'batch_count' referenced before assignment
```

(If I set batch_count to 0 outside the "for bi" loop, I then get the same kind of error for bi).

I suppose I am not using your code correctly.
Could you tell me where I am wrong ?

Besides could you tell me how long an epoch is supposed to take approximately ?

Thanks,
Boris.

**Comment by xamyzhao** [comment]
Hi Boris! experiment_engine.py initializes batch_count during training, and your training set size is 0 (transform_models.py computes the training set size based on vols_unlabeled_train.shape[0]). You should be able to fix this temporarily by modifying get_n_train() in transform_models.py. Thanks for pointing this out -- I will work on a fix.

**Comment by xamyzhao** [comment]
@BorisMansencal also -- transform_models.py is designed to learn transform models based on the transformations between labeled examples and unlabeled examples. Modying get_n_train() might get the code to run, but it probably won't learn the transform models you want. You should make sure that you have some unlabeled examples that you can learn transformations from.

The duration of an epoch depends on the size of your dataset. On the MRI dataset we used, each example took around 0.3-1s to run, and we define the number of examples in an epoch as (roughly) the number of unlabeled examples.

**Comment by BorisMansencal** [comment]
@xamyzhao Thanks a lot. If I add some unlabeled examples it seems to train the flow-fwd model.

However I am not sure I have completely understood how to set the parameters, in particular n_shots, n_unlabeled and use_subjects_as_source, to train a flow model (first fwd then bck). 
I must specify a unique atlas, via use_subjects_as_source, and I need only one labeled image, right ? What is learned when I have several labeled images ?

**Comment by BorisMansencal** [comment]
@xamyzhao Actually, I don't understand your phrase "You should make sure that you have some unlabeled examples that you can learn transformations from.". Is it just due to how the code currently is or is there a deeper reason ?
If there are several labeled examples, we could use these labeled examples as unlabeled examples, as long as we do not give the two same examples to train the model. This way, we would have more pairs and the model would possibly train better. Am I wrong ?

**Comment by xamyzhao** [comment]
@BorisMansencal conceptually, it is perfectly fine to learn the transformations between any "source" and "target" volumes. In my earlier comment, I meant that the code in transform_models.py learns the transformations between X_source_train and X_target_train. By default, these are loaded in mri_loader.py as vols_unlabeled_train and vols_labeled_train respectively. You could certainly load your labeled examples as target examples, but you might have to modify mri_loader.py to load your desired volumes into the correct variables. Hope that clears things up.
